input_max_length: 65536,65536,65536
datasets: narrativeqa_64836,infbench_qa_eng_64926,infbench_choice_eng_64926
generation_max_length: 100,10,10
test_files: ',,'
demo_files: ',,'
use_chat_template: true
shots: 2
stop_new_line: false
