input_max_length: 8192,8192,8192
datasets: narrativeqa_7892,infbench_qa_eng_7982,infbench_choice_eng_7982
generation_max_length: 100,10,10
test_files: ',,'
demo_files: ',,'
use_chat_template: true
shots: 2
stop_new_line: false
