input_max_length: 32768
datasets: ruler_niah_mv
generation_max_length: 20
test_files: data/ruler/niah_multivalue/validation_32768.jsonl
demo_files: ''
use_chat_template: false
shots: 0
stop_new_line: false
